# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-31 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000, verbose_name='內容')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵稱')),
                ('website', models.URLField(verbose_name='網站')),
                ('email', models.EmailField(max_length=254, verbose_name='郵箱')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '刪除')], default=1, verbose_name='狀態')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='評論目標')),
            ],
            options={
                'verbose_name': '評論',
                'verbose_name_plural': '評論',
                'db_table': 'Comment',
            },
        ),
    ]
